steps:
  # Setup GOPATH
- name: 'ubuntu'
  entrypoint: 'bash'
  volumes:
  - name: 'go_files'
    path: '/gopath'
  args:
  - '-c'
  - |
      mkdir -p /gopath/src/github.com/wgoodall01/
      cp -r /workspace /gopath/src/github.com/wgoodall01/terse


  # backend: Install dependencies
- name: 'gcr.io/cloud-builders/go'
  volumes:
  - name: 'go_files'
    path: '/gopath'
  args: ['get', './...']
  env: ['GOPATH=/gopath']
  dir: '/gopath/src/github.com/wgoodall01/terse'

  # backend: Test
- name: 'gcr.io/cloud-builders/go'
  volumes:
  - name: 'go_files'
    path: '/gopath'
  args: ['test', './...']
  env: ['GOPATH=/gopath']
  dir: '/gopath/src/github.com/wgoodall01/terse'

  # frontend: install deps
- name: 'node:10.8.0'
  entrypoint: 'yarn'
  args: ['install', '--production']
  volumes:
  - name: 'go_files'
    path: '/gopath'
  dir: '/gopath/src/github.com/wgoodall01/terse/client'

  # frontend: build assets
- name: 'node:10.8.0'
  entrypoint: 'yarn'
  args: ['run', 'build']
  volumes:
  - name: 'go_files'
    path: '/gopath'
  dir: '/gopath/src/github.com/wgoodall01/terse/client'

  # Deploy everything to App Engine
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy'] 
  env: ['GOPATH=/gopath']
  volumes:
  - name: 'go_files'
    path: '/gopath'
  dir: '/gopath/src/github.com/wgoodall01/terse'

timeout: 500s
